TASKS_GRPC=${SERVICE_NAME}_grpc

build-tasks-grpc:
	@echo "Building ${TASKS_GRPC}:${GIT_SHA}"
	CGO_ENABLED=0 \
	GOOS=linux \
	GOARCH=amd64 \
	go build -gcflags='-m -m' -o ${TASKS_GRPC} cmd/${TASKS_GRPC}/main.go
.PHONY: build-tasks-grpc

start-tasks-grpc: build-tasks-grpc
	@echo "Starting ${TASKS_GRPC}:${GIT_SHA}"
	APP_ENV=development \
	go run cmd/${TASKS_GRPC}/main.go
.PHONY: start-tasks-grpc